export const LOAD_INITIAL_USER_STATE = "LOAD_INITIAL_ACTOR_STATE"
export const LOGOUT_USER_STATE = "LOGOUT_USER_STATE"
export const SET_HOME = "SET_HOME"
export const SET_HOME_TASKS = "SET_HOME_TASKS"
